name: Update wesbite Content

on:
  push:
    branches:
      - main 
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Upload File to AWS S3
        uses: ramonpaolo/action-upload-s3@main
        with:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET}}
          AWS_REGION: us-east-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  
          # path of local file to upload
          local_path_upload: website_code/index.html
  
          # path to upload bucket on aws s3
          bucket_path_upload: /
          
          # the name of key/object to store in S3
          name_to_save_on_s3: index.html
